{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gainsight.px",
    "module": "mobile-sdk",
    "version": "1.12.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-1.12.4.aar",
          "url": "mobile-sdk-1.12.4.aar",
          "size": 308703,
          "sha512": "00e22b43125b21d6280777fed18ab9796f93bef509a40239821e8a777fac04c5b37c31b557d132336dc688eebcb4b7ac80c46e65bc637ead6eba2d12e9a46506",
          "sha256": "bc47443626e87c4069acdd3bf9db15ea382b8f4cecc4636e6f7e8cc9a0d3018f",
          "sha1": "297f55d30d08f9862ab9f061f9118216b84cac13",
          "md5": "4e290d63abd16dc4c21437f2697056b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-1.12.4.aar",
          "url": "mobile-sdk-1.12.4.aar",
          "size": 308703,
          "sha512": "00e22b43125b21d6280777fed18ab9796f93bef509a40239821e8a777fac04c5b37c31b557d132336dc688eebcb4b7ac80c46e65bc637ead6eba2d12e9a46506",
          "sha256": "bc47443626e87c4069acdd3bf9db15ea382b8f4cecc4636e6f7e8cc9a0d3018f",
          "sha1": "297f55d30d08f9862ab9f061f9118216b84cac13",
          "md5": "4e290d63abd16dc4c21437f2697056b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile-sdk-1.12.4-javadoc.jar",
          "url": "mobile-sdk-1.12.4-javadoc.jar",
          "size": 542217,
          "sha512": "ce25cda8bdbdbc6b58f856dc429b67f7de89eeeec0c9243605ce652055e0dc62f81635e3b9d15b38273394d44b97fb9e4e5f437eeea5ff1f298803f6247f69e4",
          "sha256": "3c521af2b2e651937630e12846399a70887d22f7b04ba19e7e1a64b63ab558fc",
          "sha1": "76429b0db5b8fd19b8b2c79e3e49debf248fce55",
          "md5": "bb938cc0789494f9db6a58c86a88d0fa"
        }
      ]
    }
  ]
}
