{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gainsight.px",
    "module": "mobile-sdk",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-1.12.0.aar",
          "url": "mobile-sdk-1.12.0.aar",
          "size": 304768,
          "sha512": "d92103b6a2787381d55b1fdc9a2460e4a2de4d1e4bf860f0f561a48bcf262cd65bad742a7d07efbfbd6c21fdead7dddddff72dec124e97bf98d34e730241bfa9",
          "sha256": "3f51ca7fbbaf6dff2be0d86876e7557ba40abe3fe98fd24b1647e89fc3c02378",
          "sha1": "fe9813eaf2fd67b1625a3764cb910c5df5003045",
          "md5": "0b06e6ad5b2b8636352667cbed7ea039"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-sdk-1.12.0.aar",
          "url": "mobile-sdk-1.12.0.aar",
          "size": 304768,
          "sha512": "d92103b6a2787381d55b1fdc9a2460e4a2de4d1e4bf860f0f561a48bcf262cd65bad742a7d07efbfbd6c21fdead7dddddff72dec124e97bf98d34e730241bfa9",
          "sha256": "3f51ca7fbbaf6dff2be0d86876e7557ba40abe3fe98fd24b1647e89fc3c02378",
          "sha1": "fe9813eaf2fd67b1625a3764cb910c5df5003045",
          "md5": "0b06e6ad5b2b8636352667cbed7ea039"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile-sdk-1.12.0-javadoc.jar",
          "url": "mobile-sdk-1.12.0-javadoc.jar",
          "size": 538300,
          "sha512": "4b5f8a91c6e2ae3fa7428c071c8166c06615a315e6f5f0d083c94d0fbdd633cdc9ed179bfc787dd2f0387b127779ee6ee21272555c7b33acb79f417146ccfeaf",
          "sha256": "ef4f9070c3c21bb3a3c17bfe5a614e283f87296c75f695334b9f2a7e20d6af02",
          "sha1": "18e19c02ef7bbdc5a01a0fa5220c00dc36fc162a",
          "md5": "0a6e41e619515e66dfdcd3898c6f5845"
        }
      ]
    }
  ]
}
